seed: 1
num_requests: 0
num_sequences: 0
model_kv_bytes_per_token: 256
cache_capacity_bytes: 268435456
policy: lru
reuse_model: zipf
workload:
  type: trace
  trace_path: ../datasets/mooncake_trace.jsonl
block_size_tokens: 512
time_model:
  compute_tokens_per_ms: 1200
  l1_bandwidth_bytes_per_ms: 7.5e8
  l2_bandwidth_bytes_per_ms: 3.0e8
  miss_bandwidth_bytes_per_ms: 6.0e7
  hit_compute_fraction: 0.2
